import { Label } from "@/types/label";

export function translateLabels(label: Label) {
	switch (label) {
		case "news":
			return "ニュース";
		case "politics":
			return "政治";
		case "economics":
			return "経済";
		case "health":
			return "健康";
		case "sports":
			return "スポーツ";
		case "entertainment":
			return "エンターテインメント";
		case "art":
			return "アート";
		case "cooking":
			return "料理";
		case "travel":
			return "旅行";
		case "fashion":
			return "ファッション";
		case "beauty":
			return "美容";
		case "pets":
			return "ペット";
		case "parenting":
			return "育児";
		case "education":
			return "教育";
		case "environment":
			return "環境";
		case "climate":
			return "気候";
		case "space":
			return "宇宙";
		case "mental_health":
			return "メンタルヘルス";
		case "fitness":
			return "フィットネス";
		case "reading":
			return "読書";
		case "history":
			return "歴史";
		case "philosophy":
			return "哲学";
		case "religion":
			return "宗教";
		case "culture":
			return "文化";
		case "volunteering":
			return "ボランティア";
		case "social_issues":
			return "社会問題";
		case "law":
			return "法律";
		case "taxes":
			return "税金";
		case "investment":
			return "投資";
		case "real_estate":
			return "不動産";
		case "diy":
			return "DIY";
		case "gardening":
			return "ガーデニング";
		case "interior_design":
			return "インテリア";
		case "automotive":
			return "自動車";
		case "gaming":
			return "ゲーム";
		case "anime_manga":
			return "アニメ・漫画";
		case "creative_works":
			return "創作";
		case "photography_video":
			return "写真・動画";
		case "media":
			return "メディア";
		case "marketing":
			return "マーケティング";
		case "branding":
			return "ブランディング";
		case "entrepreneurship":
			return "起業";
		case "remote_work":
			return "リモートワーク";
		case "data_science":
			return "データサイエンス";
		case "iot":
			return "IoT";
		case "robotics_engineering":
			return "ロボット工学";
		case "biotechnology":
			return "バイオテクノロジー";
		case "nanotechnology":
			return "ナノテクノロジー";
		case "energy_technology":
			return "エネルギー技術";
		case "archaeology":
			return "考古学";
		case "psychology":
			return "心理学";
		case "sociology":
			return "社会学";
		case "anthropology":
			return "人類学";
		case "geography":
			return "地理学";
		case "geology":
			return "地質学";
		case "meteorology":
			return "気象学";
		case "disaster_emergency_management":
			return "災害・防災";
		case "urban_planning":
			return "都市計画";
		case "architecture":
			return "建築";
		case "agriculture":
			return "農業";
		case "nutrition_science":
			return "栄養学";
		case "sleep_science":
			return "睡眠科学";
		case "productivity":
			return "生産性";
		case "leadership":
			return "リーダーシップ";
		case "international_relations":
			return "国際関係";
		case "future_predictions":
			return "未来予測";
		case "events":
			return "イベント";
		case "community":
			return "コミュニティ";
		case "trends":
			return "トレンド";
		case "lifestyle":
			return "ライフスタイル";
		case "software_development":
			return "ソフトウェア開発";
		case "programming_languages":
			return "プログラミング言語";
		case "web_development":
			return "ウェブ開発";
		case "mobile_app_development":
			return "モバイルアプリ開発";
		case "debugging_techniques":
			return "デバッギング技術";
		case "algorithms_mathematics":
			return "アルゴリズムと数学";
		case "database_design":
			return "データベース設計";
		case "cloud_computing":
			return "クラウドコンピューティング";
		case "server_management":
			return "サーバー管理";
		case "network_security":
			return "ネットワークセキュリティ";
		case "cryptography":
			return "暗号技術";
		case "artificial_intelligence":
			return "人工知能";
		case "machine_learning":
			return "機械学習";
		case "deep_learning":
			return "ディープラーニング";
		case "computer_vision":
			return "コンピュータビジョン";
		case "natural_language_processing":
			return "自然言語処理";
		case "blockchain_technology":
			return "ブロックチェーン技術";
		case "quantum_computing":
			return "量子コンピューティング";
		case "edge_computing":
			return "エッジコンピューティング";
		case "microservices_architecture":
			return "マイクロサービスアーキテクチャ";
		case "devops":
			return "DevOps";
		case "container_technology":
			return "コンテナ技術";
		case "ci_cd":
			return "CI/CD";
		case "test_automation":
			return "テスト自動化";
		case "ux_ui_design":
			return "UX/UIデザイン";
		case "agile_development_methodologies":
			return "アジャイル開発手法";
		case "open_source":
			return "オープンソース";
		case "version_control":
			return "バージョン管理";
		case "api_design":
			return "API設計";
		case "performance_optimization":
			return "パフォーマンス最適化";
		default:
			return label;
	}
}
